script: ./script/cibuild
before_install:
  - gem update --system 2.1.11
  - script/bootstrap
rvm: 
  - 1.9.3
env:
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.2.4
  - PUPPET_VERSION=3.3.2
  - PUPPET_VERSION=3.4.1
